"""Add rating to restaurant

Revision ID: 169be2501cc6
Revises: 0d11b2ad38cb
Create Date: 2026-03-11 07:17:18.060106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169be2501cc6'
down_revision: Union[str, None] = '0d11b2ad38cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'rating')
    # ### end Alembic commands ###
