"""add_driver_location_tracking_columns

Revision ID: 2995ac7baddc
Revises: 90398d245386
Create Date: 2026-03-06 12:53:33.504469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2995ac7baddc'
down_revision: Union[str, None] = '90398d245386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('current_lat', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('current_lng', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'last_seen')
    op.drop_column('drivers', 'current_lng')
    op.drop_column('drivers', 'current_lat')
    # ### end Alembic commands ###
