"""add_financial_fields_to_orders

Revision ID: 2d4f3f813f73
Revises: 52ffc5e391d2
Create Date: 2026-03-03 08:21:34.724940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4f3f813f73'
down_revision: Union[str, None] = '52ffc5e391d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('commission_amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('payout_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payout_amount')
    op.drop_column('orders', 'commission_amount')
    # ### end Alembic commands ###
