"""add_driver_model_and_order_delivery_fields

Revision ID: 4e3ecbb33a2d
Revises: 4ca00eaa7810
Create Date: 2026-03-06 11:11:29.517888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3ecbb33a2d'
down_revision: Union[str, None] = '4ca00eaa7810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'DRIVER'")
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.add_column('orders', sa.Column('delivery_fee', sa.Float(), nullable=True, server_default='2.0'))
    op.add_column('orders', sa.Column('restaurant_accepted_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('ready_for_pickup_at', sa.DateTime(), nullable=True))
    op.drop_constraint('orders_driver_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_driver_id_drivers', 'orders', 'drivers', ['driver_id'], ['id'])
    op.alter_column('orders', 'delivery_fee', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_driver_id_drivers', 'orders', type_='foreignkey')
    op.create_foreign_key('orders_driver_id_fkey', 'orders', 'users', ['driver_id'], ['id'])
    op.drop_column('orders', 'ready_for_pickup_at')
    op.drop_column('orders', 'restaurant_accepted_at')
    op.drop_column('orders', 'delivery_fee')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
