"""finalize_order_financial_columns

Revision ID: 6c365a88f842
Revises: 4e3ecbb33a2d
Create Date: 2026-03-06 11:33:33.266776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c365a88f842'
down_revision: Union[str, None] = '4e3ecbb33a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('platform_fee', sa.Float(), nullable=True, server_default='1.5'))
    op.alter_column('orders', 'platform_fee', nullable=False, server_default=None)
    op.alter_column('orders', 'payout_amount', new_column_name='restaurant_payout')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'restaurant_payout', new_column_name='payout_amount')
    op.drop_column('orders', 'platform_fee')
    # ### end Alembic commands ###
