"""sync_database_schema

Revision ID: a2b861a22462
Revises: 2d4f3f813f73
Create Date: 2026-03-05 16:19:50.787113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b861a22462'
down_revision: Union[str, None] = '2d4f3f813f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['driver_id'], ['id'])
    op.add_column('restaurants', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'image_url')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'driver_id')
    # ### end Alembic commands ###
